language: android
sudo: false
jdk: oraclejdk8

android:
  components:
  - build-tools-25.0.0
  - android-25
  - extra-android-m2repository
  - extra-android-support

script:
- ./gradlew assembleRelease

before_install:
- gem install mime-types -v 2.6.2
- openssl aes-256-cbc -K $encrypted_9832fa0e04b3_key -iv $encrypted_9832fa0e04b3_iv
  -in xifan.jks.enc -out ./xifan.jks -d
- gem install fir-cli

after_deploy:
- fir p app/build/outputs/apk/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
